version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.8
    working_directory: ~/project

jobs:
  terraform-validate:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Init & Validate
          command: |
            cd terraform
            terraform init
            terraform validate

  terraform-plan:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            cd terraform
            terraform init
            terraform plan \
              -var "admin_username=labadmin" \
              -var "admin_password=$LAB_ADMIN_PASSWORD"

  terraform-apply:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            cd terraform
            terraform init
            terraform apply -auto-approve \
              -var "admin_username=labadmin" \
              -var "admin_password=$LAB_ADMIN_PASSWORD"

  terraform-destroy:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Destroy
          command: |
            cd terraform
            terraform init
            terraform destroy -auto-approve \
              -var "admin_username=labadmin" \
              -var "admin_password=$LAB_ADMIN_PASSWORD"

workflows:
  terraform:
    jobs:
      - terraform-validate
      - terraform-plan:
          requires:
            - terraform-validate
      - hold-apply:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - terraform-plan
      - hold-destroy:
          type: approval
          requires:
            - terraform-apply
      - terraform-destroy:
          requires:
            - hold-destroy